//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIAssistantControlApp.MIOMService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MIOMService.IMIOMService")]
    public interface IMIOMService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMIOMService/GetState", ReplyAction="http://tempuri.org/IMIOMService/GetStateResponse")]
        MultimediaIOManagerService.Enums.MIOMServiceState GetState();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMIOMService/GetState", ReplyAction="http://tempuri.org/IMIOMService/GetStateResponse")]
        System.Threading.Tasks.Task<MultimediaIOManagerService.Enums.MIOMServiceState> GetStateAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMIOMServiceChannel : AIAssistantControlApp.MIOMService.IMIOMService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MIOMServiceClient : System.ServiceModel.ClientBase<AIAssistantControlApp.MIOMService.IMIOMService>, AIAssistantControlApp.MIOMService.IMIOMService {
        
        public MIOMServiceClient() {
        }
        
        public MIOMServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MIOMServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MIOMServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MIOMServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public MultimediaIOManagerService.Enums.MIOMServiceState GetState() {
            return base.Channel.GetState();
        }
        
        public System.Threading.Tasks.Task<MultimediaIOManagerService.Enums.MIOMServiceState> GetStateAsync() {
            return base.Channel.GetStateAsync();
        }
    }
}
